# Auto-generated by imp - DO NOT EDIT
# Regenerate with: nix run .#imp-flake
{
  description = "NixOS + Home Manager configuration using imp";
  inputs = {
    # Core inputs
    flake-parts.url = "github:hercules-ci/flake-parts";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    imp.url = "github:imp-nix/imp.lib";
    imp-graph.url = "github:imp-nix/imp.graph";
    imp-graph.inputs.nixpkgs.follows = "nixpkgs";
    imp-refactor.url = "github:imp-nix/imp.refactor";
    imp-refactor.inputs.nixpkgs.follows = "nixpkgs";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # Collected from __inputs
    nur.url = "github:nix-community/NUR";
    nur.inputs.nixpkgs.follows = "nixpkgs";
    treefmt-nix.url = "github:numtide/treefmt-nix";
  };
  outputs = inputs: import ./nix/flake inputs;
}
